add and delete some files

diff --git a/mtable b/mtable
--- a/mtable
+++ b/mtable
@@ -3,16 +3,15 @@
 #Script to test for loop
 #
 #
-if [ $# -eq 0 ]
-then
-echo "Error - Number missing form command line argument"
-echo "Syntax : $0 number"
-echo "Use to print multiplication table for given number"
-exit 1
+if [ $# -eq 0 ]; then
+    echo "Error - Number missing form command line argument"
+    echo "Syntax : $0 number"
+    echo "Use to print multiplication table for given number"
+    exit 1
 fi
+
 n=$1
-for i in 1 2 3 4 5 6 7 8 9 10
-do
-echo "$n * $i = `expr $i \* $n`"
+for i in 1 2 3 4 5 6 7 8 9 10; do
+    echo "$n * $i = `expr $i \* $n`"
 done
 
